import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import  Layout  from "../components/Layout/Layout";

import "./globals.css";
import DirectionProvider from "@/direction-provider";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <DirectionProvider>
          <ReduxProvider>
            <Layout>{children}</Layout>
          </ReduxProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
